"""create moleculas table

Revision ID: b54685b02505
Revises: 
Create Date: 2026-06-22 21:00:28.089409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54685b02505'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moleculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('molecular_formula', sa.String(), nullable=True),
    sa.Column('molar_mass', sa.Float(), nullable=True),
    sa.Column('SMILES', sa.String(), nullable=True),
    sa.Column('melting_range', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moleculas_SMILES'), 'moleculas', ['SMILES'], unique=False)
    op.create_index(op.f('ix_moleculas_id'), 'moleculas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moleculas_id'), table_name='moleculas')
    op.drop_index(op.f('ix_moleculas_SMILES'), table_name='moleculas')
    op.drop_table('moleculas')
    # ### end Alembic commands ###
